
server:
  port: 5010

spring:
  application:
    name: gateway-zuul-client

eureka:
  client:
    service-url:
      # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://discovery-server:5001/eureka/,http://discovery-server-slave:5002/eureka/
  instance:
    hostname: gateway-zuul-client
    # lease-expiration-duration-in-seconds：服务失效时间，默认值90秒
    lease-expiration-duration-in-seconds: 20
    # lease-renewal-interval-in-seconds：服务续约(renew)的间隔，默认为30秒
    lease-renewal-interval-in-seconds: 5

    # 下面都⾮必须，如果不配置，将默认使⽤http://GATEWAY:GATEWAY_PORT/想要访问的Eureka服务applicationName/**
    # 路由到： http://想要访问的Eureka服务applicationName:该服务端⼝/**
zuul:
  routes:
   # 可以随便写，在zuul上⾯唯⼀即可，当这⾥的值等于applicationName时， service-id可以不写
    ribbon-hystrix:
      path: /ribbon-hystrix/**
      service-id: ribbon-hystrix-client
       # zuul gateway 也可以脱离eureka独立运行
#      service-id: http://ribbon-hystrix-client:5007/

