
server:
  port: 5001

spring:
  application:
    name: eureka-discovery-server

eureka:
  instance:
    hostname: discovery-server
  client:
    service-url:
      # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://discovery-server-slave:5002/eureka/


