
server:
  port: 5010

spring:
  application:
    name: hystrix-turbine

eureka:
  client:
    service-url:
      # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://discovery-server:5001/eureka/,http://discovery-server-slave:5002/eureka/

turbine:
  aggregator:
    cluster-config: default
  app-config: ribbon-hystrix-client
