
server:
  port: 5004

spring:
  application:
    name: eureka-discovery-client

eureka:
  client:
    service-url:
      # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://discovery-server:5001/eureka/,http://discovery-server-slave:5002/eureka/
  instance:
    hostname: discovery-client
    # lease-expiration-duration-in-seconds：服务失效时间，默认值90秒
    lease-expiration-duration-in-seconds: 20
    # lease-renewal-interval-in-seconds：服务续约(renew)的间隔，默认为30秒
    lease-renewal-interval-in-seconds: 5
